from pydantic import BaseModel, Field
from typing import Dict, Any, Optional, List

class Document(BaseModel):
    """Normalized representation of a clinical document."""
    id: str
    source: str
    title: Optional[str] = "Untitled"
    sections: Dict[str, str] = Field(default_factory=dict)
    text: str
    metadata: Dict[str, Any] = Field(default_factory=dict)

class Chunk(BaseModel):
    """A retrievable unit of text derived from a Document."""
    parent_doc_id: str
    section: str
    chunk_index: int
    text: str

from typing import List
from pydantic import BaseModel, Field

# ... (Keep your existing Document and Chunk classes here) ...

class Claim(BaseModel):
    """Represents a single factual claim extracted or generated by the AI."""
    text: str = Field(..., description="The specific factual claim made by the AI")
    source_id: str = Field(..., description="The ID of the source document (e.g., PMID or NCT ID)")
    source_chunk_id: int = Field(..., description="The specific chunk ID from the database that supports this claim")

class ClinicalAnswer(BaseModel):
    """The final structured answer returned to the user."""
    question: str = Field(..., description="The original clinical question asked by the user")
    claims: List[Claim] = Field(..., description="A list of distinct, cited claims answering the question")
    summary: str = Field(..., description="A short, synthesized summary of the claims")
    verified: bool = Field(default=False, description="Flag indicating if the claims have passed the verification loop")