from enum import Enum
from typing import Dict, Any, Optional, List
from pydantic import BaseModel, Field


class Label(str, Enum):
    SUPPORTED = "supported"
    UNSUPPORTED = "unsupported"
    NOT_ENOUGH_INFO = "not_enough_info"


class VerificationResult(BaseModel):
    label: Label = Field(..., description="Classification label: supported, unsupported, or not_enough_info")
    reasoning: str = Field(..., description="Brief reasoning explaining why the source chunk supports or contradicts the claim")


class Document(BaseModel):
    """Normalized representation of a clinical document."""
    id: str
    source: str
    title: Optional[str] = "Untitled"
    sections: Dict[str, str] = Field(default_factory=dict)
    text: str
    metadata: Dict[str, Any] = Field(default_factory=dict)


class Chunk(BaseModel):
    """A retrievable unit of text derived from a Document."""
    parent_doc_id: str
    section: str
    chunk_index: int
    text: str


class Claim(BaseModel):
    """Represents a single factual claim extracted or generated by the AI."""
    text: str = Field(
        ..., 
        description="The exact factual sentence/claim extracted from context"
    )
    source_id: str = Field(
        ..., 
        description="The document identifier string, e.g. PMID_12345678 or NCT12345678. Must be a direct top-level property of this claim, NOT nested in a sub-dictionary."
    )
    source_chunk_id: int = Field(
        ..., 
        description="The integer chunk_index where this fact was found. Must be a direct top-level integer property of this claim, NOT nested in a sub-dictionary."
    )


class ClinicalAnswer(BaseModel):
    """The final structured answer returned to the user."""
    question: str = Field(..., description="The original clinical question asked by the user")
    claims: List[Claim] = Field(..., description="List of Claim objects with flat top-level source_id and source_chunk_id fields")
    summary: str = Field(..., description="A short, synthesized summary of the claims")
    verified: bool = Field(default=False, description="Flag indicating if the claims have passed the verification loop")